### ISSUE TITLE
Fix "invalid sigil" rust error from ssb-multiformats

### ISSUE THREAD

**Issue by staltz** [staltz/ssb-neon-keys#1]
```
 create and load presigil-legacy async
{"curve":"ed25519","id":"xPvwSVYnIaRiAbQWndTeHq5GUmzhEX49hkurrAiJ0mI=.ed25519","private":"TW/2MuiUL2MK08qdiHsk7j/FfoE6msWRHFgtapMDD/nE+/BJVichpGIBtBad1N4erkZSbOERfj2GS6usCInSYg==.ed25519","public":"xPvwSVYnIaRiAbQWndTeHq5GUmzhEX49hkurrAiJ0mI=.ed25519"}
./ssb-neon-keys/test-extra/index.js:11
  var k2 = ssbkeys.loadSync(path);
                   ^

Error: Failed to deserialize secret file: Invalid multikey: Invalid sigil at line 1 column 78
```

Perhaps ssb-multiformats(-rs) and ssb-keyfile(-rs) don't support presigil-legacy `id` field?

----

**TODO**

- [x] Create forks of ssb-multiformats and ssb-keyfile
- [x] Consume branches of ssb-multiformats and ssb-keyfile from ssb-neon-keys 
- [ ] Get https://github.com/sunrise-choir/ssb-multiformats/pull/4 merged
- [ ] Get a new version of ssb-multiformats released
- [ ] Get a new version of ssb-keyfile released, that includes the new ssb-multiformats version
- [ ] Update ssb-keyfile in this repo

**Comment by staltz** [comment]
Maybe return `Some(&input)` here? https://github.com/sunrise-choir/ssb-multiformats/blob/d0a53815b41bddddfe610fbf884a153b7b1e9baf/src/lib.rs#L38

**Comment by staltz** [comment]
This PR or a variant of it should fix ssb-multiformats: https://github.com/sunrise-choir/ssb-multiformats/pull/3

Would require releasing a new version of ssb-multiformats, a new version of ssb-keyfile, and then updating those libs here.

**Comment by staltz** [comment]
**TODO**

- [ ] Get https://github.com/sunrise-choir/ssb-multiformats/pull/4 merged
- [ ] Get a new version of ssb-multiformats released
- [ ] Get a new version of ssb-keyfile released, that includes the new ssb-multiformats version
- [ ] Update ssb-keyfile in this repo

**Comment by staltz** [comment]
PR #19 made this issue obsolete
